# -*- coding: utf-8 -*-
"""Cópia de Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13sEZsSYDALzM_c1EOZkdfz-jAv2UDNuI
"""

# Calculadora de Juros Compostos
# Autor: Lucas + ChatGPT (para estudo)
# Linguagem: Python (Google Colab)

def calcular_juros_compostos():
    print("=== Calculadora de Juros Compostos ===\n")

    # Entradas
    aporte_inicial = float(input("Aporte inicial (R$): ") or 0)
    aporte_mensal = float(input("Aporte mensal (R$): ") or 0)
    taxa = float(input("Rendimento mensal (%): ") or 1)
    meses = int(input("Período (em meses, 1 a 180): ") or 12)

    # Processamento
    saldo = aporte_inicial
    taxa = taxa / 100  # converter para decimal

    evolucao = []  # lista pra guardar mês a mês

    for mes in range(1, meses + 1):
        juros = saldo * taxa
        saldo += juros + aporte_mensal
        evolucao.append({
            "Mês": mes,
            "Aporte": aporte_mensal if mes > 1 or aporte_inicial == 0 else aporte_inicial,
            "Juros": round(juros, 2),
            "Saldo Total": round(saldo, 2)
        })

    # Saída - mostrar evolução
    print("\n--- Evolução mês a mês ---")
    for item in evolucao:
        print(f"Mês {item['Mês']:3}: Aporte = R${item['Aporte']:8.2f} | Juros = R${item['Juros']:8.2f} | Total = R${item['Saldo Total']:10.2f}")

    print("\n--- Resultado final ---")
    total_aportes = aporte_inicial + (aporte_mensal * meses)
    total_juros = saldo - total_aportes
    print(f"Total investido: R${total_aportes:,.2f}")
    print(f"Total de juros:  R${total_juros:,.2f}")
    print(f"Valor final:     R${saldo:,.2f}")

# Chamar a função
calcular_juros_compostos()